version: "3.5"

services:

  frontend:
    build:
      context: ./angular
      dockerfile: ./Dockerfile
    ports:
      - 4205:4200

  backend:
    build:
      context: ./msnet/TestDemoApp
      dockerfile: ./Dockerfile
    ports:
      - 5005:80

